#ifndef DEFINES_H
#define DEFINED_H

#define RESOLUTION_X 800
#define RESOLUTION_Y 600
#define FULLSCREEN false
#define WINDOW_RATIO ((float)RESOLUTION_X / RESOLUTION_Y)

#define UNIFORM_ID_POSITION x
#define UNIFORM_ID_ORIENTATION o

#endif

